//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handbook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HandbookNewEntities : DbContext
    {
        public HandbookNewEntities()
            : base("name=HandbookNewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuLink> MenuLinks { get; set; }
    
        public virtual int add_menu(Nullable<int> parent_id, string name)
        {
            var parent_idParameter = parent_id.HasValue ?
                new ObjectParameter("parent_id", parent_id) :
                new ObjectParameter("parent_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_menu", parent_idParameter, nameParameter);
        }
    }
}
